// GENERATED FILE — do not edit by hand.
// Regenerate with `npm run generate:resources` after changing static/ assets.

export const IMAGE_NAMES = [
  "/images/asphalt.png",
  "/images/bandsaw-14-fence.png",
  "/images/bandsaw-14-lower.png",
  "/images/bandsaw-14-upper.png",
  "/images/bandsaw-14.png",
  "/images/benchtop-jointer.png",
  "/images/cement-floor.png",
  "/images/clamp-fixed.png",
  "/images/clamp-moving-jaw.png",
  "/images/clamp.png",
  "/images/concrete-floor-2-big.png",
  "/images/concrete-floor-2.png",
  "/images/favicon.png",
  "/images/garbage-can.png",
  "/images/grass.png",
  "/images/icons/consumable-mineralOil.png",
  "/images/icons/consumable-nails.png",
  "/images/icons/consumable-screws.png",
  "/images/icons/misc-barClamp.png",
  "/images/icons/misc-broom.png",
  "/images/icons/misc-shopVac.png",
  "/images/icons/tool-crosscutSled.png",
  "/images/icons/tool-drill.png",
  "/images/icons/tool-dustBag.png",
  "/images/icons/tool-finishingKit.png",
  "/images/icons/tool-hammer.png",
  "/images/icons/tool-handPlane.png",
  "/images/icons/tool-handSaw.png",
  "/images/icons/tool-randomOrbitSander.png",
  "/images/icons/tool-sandingBlock.png",
  "/images/icons/tool-straightLineSled.png",
  "/images/icons/upgrade-vise.png",
  "/images/jobsite-table-saw-fence.png",
  "/images/jobsite-table-saw-table.png",
  "/images/jobsite-table-saw.png",
  "/images/lunchbox-planer-bottom.png",
  "/images/lunchbox-planer-screws.png",
  "/images/lunchbox-planer-top.png",
  "/images/lunchbox-planer.png",
  "/images/main-title-logo.png",
  "/images/makeshift-bench.png",
  "/images/makeshift-bench@4x.png",
  "/images/miter-saw-rotating-base.png",
  "/images/miter-saw-stationary-base.png",
  "/images/miter-saw-top.png",
  "/images/miter-saw.png",
  "/images/operator-position.png",
  "/images/pallet.png",
  "/images/person.png",
  "/images/pickup-truck.png",
  "/images/workbench-2x2-complete.png",
  "/images/workbench-2x2-complete@4x.png",
  "/images/workbench-2x2-shadow.png",
  "/images/workbench-2x2-shadow@4x.png",
  "/images/workbench-2x2-top.png",
  "/images/workbench-2x2-top@4x.png",
  "/images/workbench-2x4-complete.png",
  "/images/workbench-2x4-complete@4x.png",
  "/images/workbench-2x4-shadow.png",
  "/images/workbench-2x4-shadow@4x.png",
  "/images/workbench-2x4-top.png",
  "/images/workbench-2x4-top@4x.png",
  "/images/workspace.png",
] as const;

export type ImageName = (typeof IMAGE_NAMES)[number];

export const SOUND_NAMES = [
  "/sounds/assembly-mallet.ogg",
  "/sounds/cash-register.ogg",
  "/sounds/commission-complete.ogg",
  "/sounds/dispose-toss.ogg",
  "/sounds/drill-driver.ogg",
  "/sounds/footstep.ogg",
  "/sounds/garage-ambient.ogg",
  "/sounds/garage-impulse-response.flac",
  "/sounds/glue-clamp.ogg",
  "/sounds/hand-sanding.ogg",
  "/sounds/hold-music.ogg",
  "/sounds/material-drop.ogg",
  "/sounds/material-pickup.ogg",
  "/sounds/miter-cut.ogg",
  "/sounds/nail-pry.flac",
  "/sounds/orbital-sander.ogg",
  "/sounds/pallet-dismantle.ogg",
  "/sounds/pallet-load.ogg",
  "/sounds/planer-cut-loop.ogg",
  "/sounds/planer-pass.ogg",
  "/sounds/planer-run-loop.ogg",
  "/sounds/planer-start.ogg",
  "/sounds/planer-stop.ogg",
  "/sounds/table-saw-rip.ogg",
  "/sounds/truck-arrive.ogg",
  "/sounds/truck-driving-loop.mp3",
  "/sounds/truck-driving-loop.ogg",
  "/sounds/truck-start.flac",
  "/sounds/ui-back.ogg",
  "/sounds/ui-book-open.ogg",
  "/sounds/ui-click-end.flac",
  "/sounds/ui-click-start.flac",
  "/sounds/ui-click.flac",
  "/sounds/ui-error.flac",
  "/sounds/ui-hover.flac",
  "/sounds/ui-notification.flac",
  "/sounds/ui-page-touch.ogg",
  "/sounds/ui-page-turn.ogg",
  "/sounds/ui-purchase.ogg",
  "/sounds/ui-tab.ogg",
] as const;

export type SoundName = (typeof SOUND_NAMES)[number];

export const FONT_NAMES = [
  "/fonts/andada-pro-variable.woff2",
  "/fonts/barlow-condensed-400.woff2",
  "/fonts/barlow-condensed-500.woff2",
  "/fonts/barlow-condensed-600.woff2",
  "/fonts/barlow-condensed-700.woff2",
  "/fonts/shantell-notes.woff2",
  "/fonts/stardos-stencil-400.woff2",
  "/fonts/stardos-stencil-700.woff2",
] as const;

export type FontName = (typeof FONT_NAMES)[number];
